### PR TITLE
Adjust precision of test statistics

### PR DESCRIPTION
**Pull request by zigaLuksic**
There are quite a few design choices being done here, so point out everything that bothers you.

### CODE REVIEW

**Review by mlubej — APPROVED** [review]
IMO the stats aren't any harder to look at now as before, so that's a plus. I think it makes sense that the amount of decimal points goes down with the larger values of floats, since precision of larger float values is also lower, as was already privately discussed.

My only concern is that the 5/10 significant digits sometimes wouldn't be enough or something, especially with larger values, but that's probably just a false feeling, since the relative error limit is always the same here, if I understand correctly

**Comment by zigaLuksic** [comment]
> My only concern is that the 5/10 significant digits sometimes wouldn't be enough or something, especially with larger values, but that's probably just a false feeling, since the relative error limit is always the same here, if I understand correctly

Yeah, 5 digits seems really low, but that's float32...

**Comment by zigaLuksic** [comment]
we could increase it to 6 and 12, which are the edges of significant digit precision, but it could be that stuff would differ due to chip differences already.

**Comment by mlubej** [comment]
> we could increase it to 6 and 12, which are the edges of significant digit precision, but it could be that stuff would differ due to chip differences already.

Mah, I'd leave it, I don't think we need to be _that_ precise for tests.

**Pull request merged**
